[google_service_account]
type = "service_account"
project_id = "engaged-patrol-462504-c4"
private_key_id = "e95c1e5c1934fef4bdf0341517c1a312d1161af3"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDVy9EcrGGoVVBT
/1l7PB0YIAcNrmK4tHVK/ma0VcvJ94l/Vvc4AFahAlE+idp17H2Qf+w2pKuGenHI
ksf64enef8QAz1fGbNu3HecEqoyiuw1rqBA3CnwuqukSX6ohslMCjIMY/Y9EiVrm
Gijgr0ZsQGwLqGqSMauDhVmFVbyg98wWf3EBUsOZbSLG2TUYCw/rxUmqQJ1QulPL
M0jTcCjD0nshuX4d5zF4xT6p8bvqGThiHxPe9/gCPaRORkXMYvBWJr1mq9fjAVUh
dUj4RvfF+gPrLeNUgOLxmukjZgBTc0ahsbD2+VbFcXzerduK5agIYpFgm7O2MF9g
FMIVCCZnAgMBAAECggEAAWDXf8ZSuNmX83qtcoBwNZQbR4jMxSEQsoOSWO5Gqo4o
ekQuwtMpu87+hBcya9ky9AgHF1EXc/39FsxvcpwbPF55foHXsIVKI1OThjGtR21K
SFvkgt5T758VcpNgTuhN5bHPNI2J62ixR9N6WPx4SUFfEPIsgbXFQ8tLyPLFDQqY
52ZgA5NfPyENt4F97IypLJvhQncnRFRrir+XhUfFjqAQpS4druQ0VykGzkARCPhc
55TxOQvZO4uoekApPhBxV6nBzXgtPfcsx9SJ2sFQUuOlpkNlPPQoXhOpSomCjYAn
zQR0sZcJ5HF9u0JYjxARnlPx7tsUKiHT24n3VQpOaQKBgQDuBsOaJ5u9WsG8tElK
uj+4Rx84w6QGVk22eKM15D7p2uDJXkf67NpyO7KX0f/1hOEWFa92zH060412LTU3
bpTVvOheYa00tEoyiQktsf2ZYSaOCYs6PPxLbFuwbLT73lKBJJFYwSy+pojugfdi
nVQDr5RiAeo/ntNJjl8KFRbseQKBgQDl8Km2xEYg54ndGWdcjoTroF/b+g3BZxK2
qz+gflCMh57SoyvqMWu8SnvMi60iK2qAP83zuatYqg7+A5h7mRKhDE7Ab1h87Grx
g1Mm6Xq0AhRFKM2uB9PFuyf5RmoSFZHlMdZLdUebKUeURQj8xTK0xOxSoj7sPO9r
oyk5W/Ux3wKBgDapIv4hnmgrkVYOaM5aWwuseYUFmINECnCe34wesDvv4bMcjZcY
EUouX2Lx/L+bFj2GGVdEunVp45CB7TifklpLGWmjMK1rwaY9RfhSaZRxdPMlSe3D
14RSi/PF4wH8GiJCDYa+RdI6WDO9cNwamRKHnaGsIukdRhQcN8MO+MaxAoGBAMpT
AuJgvdxCH5q+uaZFeUvjZ7WlxujAi0TUVj4gJzwgMW3iScfeCJA7ccc/t+3zCdkj
S1MDsnNn350/CLLos+2laL4Gu3PgixFLnqUEmAVANxnLl39kP8Eitz+t57NV63Qi
cA8heQpcPjGGtSvFUKKjC9aCEJ/J1ll9zc48zfk9AoGAOdjeIvVtqULP6z1dbXw/
EbhefNn1l17fPZPuqx7UUQEY7lYNKGqCV5IqUpLuRxaO7ff4jEfZ15gHzjqO9ofL
MsD8ZZVg5HzxT/TWr8cXs4OXNa8p8Xm4EC3jPdzOpCj00VNpGmd/jKO0o+v2YXqY
VgAC1i3YeJADiomVrZhGQDc=
-----END PRIVATE KEY-----
"""
client_email = "vision-api-service-account@engaged-patrol-462504-c4.iam.gserviceaccount.com"
client_id = "111224332211572570409"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/vision-api-service-account%40engaged-patrol-462504-c4.iam.gserviceaccount.com"
universe_domain = "googleapis.com"